#!/bin/bash
# Install the sandbox must-use plugins on every web-container start.
#
# Replaces what .local/wp-entrypoint.sh used to do under Docker Compose. Two
# things got simpler in the move to DDEV:
#
#   * No UID/GID remapping. DDEV already runs the web container as the host
#     user, so files written here are owned correctly with no groupmod/usermod.
#   * No separate read-only mount for the sources. The old compose file had to
#     mount .local/wp-mu-plugins/ outside the docroot because .local was masked
#     by an anonymous volume; DDEV bind-mounts the whole project, so the sources
#     are simply readable at $DDEV_APPROOT/.local/wp-mu-plugins/.
#
# What has NOT changed is the reason for the generated stub. wp_get_mu_plugins()
# (wp-includes/load.php) readdir()s wp-content/mu-plugins and takes only the
# *.php sitting directly inside it — WordPress never recurses. So the copies go
# in local-mu-plugins/ to stay clearly separate from the project's own mu-plugins
# (Pantheon's loader.php and pantheon-mu-plugin/ live in the same folder), and a
# generated top-level stub is what actually loads them. Delete the stub and
# everything in the subdirectory silently stops loading.
#
# The "00-" prefix is load-bearing: mu-plugins load in filename order, and
# 01-sandbox-page-cache.php must register its filter before Pantheon's
# loader.php constructs Pantheon_Cache.
#
# ---------------------------------------------------------------------------
# IMPORTANT: DDEV *sources* every .sh in this directory from its entrypoint
# ("source /mnt/ddev_config/web-entrypoint.d/<file>"), it does not execute it in
# a child process. So this whole script runs inside a subshell: `exit` would
# otherwise terminate the entrypoint itself and the container would die on
# startup, and `set -e`/`set -u` would leak into the rest of the entrypoint.
# Any early return must stay inside the parentheses below.
# ---------------------------------------------------------------------------
(
    set -eu

    # Sandbox-only, same gate the installed files use.
    [ "${IS_DDEV_PROJECT:-}" = "true" ] || exit 0

    APPROOT="${DDEV_APPROOT:-/var/www/html}"
    MU_SRC_DIR="$APPROOT/.local/wp-mu-plugins"
    MU_ROOT_DIR="$APPROOT/wp-content/mu-plugins"
    MU_DEST_DIR="$MU_ROOT_DIR/local-mu-plugins"
    MU_LOADER="$MU_ROOT_DIR/00-local-mu-plugins.php"

    # No sources, nothing to do.
    [ -d "$MU_SRC_DIR" ] || exit 0

    # No wp-content yet. This scaffolding is often dropped into a project before
    # WordPress is present, and this repository has no WordPress of its own.
    # Exit quietly rather than creating a stray wp-content/ that would confuse
    # WordPress (and WP-CLI) later.
    [ -d "$APPROOT/wp-content" ] || exit 0

    mkdir -p "$MU_DEST_DIR"

    # Refresh the copies. cmp first so an unchanged file keeps its mtime, which
    # keeps opcache and any file watchers quiet.
    for mu_src in "$MU_SRC_DIR"/*.php; do
        [ -f "$mu_src" ] || continue
        mu_dest="$MU_DEST_DIR/$(basename "$mu_src")"
        cmp -s "$mu_src" "$mu_dest" || cp "$mu_src" "$mu_dest"
    done

    # Drop copies whose source is gone, so renaming or deleting a sandbox
    # mu-plugin actually takes effect instead of leaving the old one loading
    # forever. Only files we generated are ever removed — the marker is checked
    # every time. Written as an if, not `grep -q ... && rm`, because under
    # `set -e` a non-matching grep makes that whole list return non-zero and
    # aborts the script.
    for mu_old in "$MU_DEST_DIR"/*.php; do
        [ -f "$mu_old" ] || continue
        if [ -f "$MU_SRC_DIR/$(basename "$mu_old")" ]; then
            continue
        fi
        if grep -q '#.local-generated' "$mu_old" 2>/dev/null; then
            rm -f "$mu_old"
        fi
    done

    # Clear out copies from the pre-DDEV layout, which installed these at the
    # top level. Left in place they would load a second time alongside the
    # local-mu-plugins/ copy. Again, only ever files carrying our marker.
    for mu_legacy in "$MU_ROOT_DIR"/[0-9][0-9]-sandbox-*.php; do
        [ -f "$mu_legacy" ] || continue
        if grep -q '#.local-generated' "$mu_legacy" 2>/dev/null; then
            rm -f "$mu_legacy"
        fi
    done

    cat > "$MU_LOADER" <<'LOADER'
<?php

/**
 * #.local-generated: Automatically generated WordPress must-use plugin.
 * .local manages this file and overwrites it on every container start.
 *
 * Generated by: .ddev/web-entrypoint.d/10-sandbox-mu-plugins.sh
 *
 * Loads the sandbox mu-plugins that live in local-mu-plugins/. WordPress only
 * loads *.php sitting directly in wp-content/mu-plugins — wp_get_mu_plugins()
 * readdir()s that one directory and does not recurse — so without this stub
 * everything in the subdirectory is invisible to it.
 *
 * The "00-" prefix is load-bearing: mu-plugins load in filename order, and
 * 01-sandbox-page-cache.php must register its filter before Pantheon's
 * loader.php constructs Pantheon_Cache.
 *
 * @package .local
 */

// Sandbox-only. IS_DDEV_PROJECT is set in every DDEV web container and nowhere
// else, so a stray copy of this file on a real host does nothing at all.
if (getenv('IS_DDEV_PROJECT') !== 'true') {
    return;
}

$local_mu_dir = __DIR__ . '/local-mu-plugins';
if (is_dir($local_mu_dir)) {
    // sort() to make load order match the filename prefixes, the same ordering
    // WordPress applies to the mu-plugins directory itself. glob() is already
    // sorted, but this does not depend on that.
    $local_mu_files = glob($local_mu_dir . '/*.php');
    if ($local_mu_files) {
        sort($local_mu_files);
        foreach ($local_mu_files as $local_mu_file) {
            require_once $local_mu_file;
        }
    }
}

// mu-plugins are included at global scope, so anything left behind becomes a
// global. Clean up after ourselves.
unset($local_mu_dir, $local_mu_files, $local_mu_file);
LOADER

    echo "sandbox: installed mu-plugins into wp-content/mu-plugins/local-mu-plugins/"
# `|| true` so a failure in here can never stop the web container from starting.
# A broken sandbox mu-plugin installer should be a visible warning in the logs,
# not an unbootable site.
) || echo "sandbox: mu-plugin install skipped (non-fatal)" >&2
