#!/bin/bash
# Remap the container's www-data to the host user's UID/GID so Apache can
# read AND write the bind-mounted project files — which are owned on the host
# by that user — WITHOUT changing any ownership on the host. You keep full edit
# rights to every file; Apache just shares your UID, so it can write .htaccess,
# wp-content/uploads, etc.
#
# HOST_UID / HOST_GID are injected by docker-compose (default 1000:1000).
set -e

HOST_UID="${HOST_UID:-1000}"
HOST_GID="${HOST_GID:-1000}"

if [ "$(id -g www-data)" != "$HOST_GID" ]; then
  groupmod -o -g "$HOST_GID" www-data
fi
if [ "$(id -u www-data)" != "$HOST_UID" ]; then
  usermod -o -u "$HOST_UID" www-data
fi

# The remap orphans Apache's own runtime/log dirs (created under the old UID);
# re-chown them so logging and pid files keep working.
chown -R www-data:www-data /var/run/apache2 /var/log/apache2 /var/lib/apache2 2>/dev/null || true

# Install the sandbox mu-plugins:
#   00-sandbox-mailpit.php    sends wp_mail() to the mail catcher instead of PHP
#                             mail() — the image has no MTA behind mail(), so
#                             without it mail vanishes silently.
#   01-sandbox-page-cache.php zeroes the Pantheon page-cache TTL, so an edited
#                             template shows up on reload instead of being
#                             pinned in the browser for a week.
#
# They are copied in as real files rather than bind-mounted, so the wp-cli and
# claude containers — which share the docroot bind mount but not this entrypoint
# — pick them up too. Refreshed on every start; the copies are git-ignored.
#
# They go in their own local-mu-plugins/ subdirectory to keep the sandbox's
# files clearly separate from the project's own (Pantheon's loader.php and
# pantheon-mu-plugin/ live in the same folder). WordPress does NOT recurse into
# subdirectories — wp_get_mu_plugins() readdir()s wp-content/mu-plugins and
# takes only *.php sitting directly in it — so a generated top-level stub is
# what actually loads them. See MU_LOADER below.
MU_ROOT_DIR="/var/www/html/wp-content/mu-plugins"
MU_SRC_DIR="/usr/local/share/sandbox-mu-plugins"
MU_DEST_DIR="$MU_ROOT_DIR/local-mu-plugins"
MU_LOADER="$MU_ROOT_DIR/00-local-mu-plugins.php"
if [ -d "$MU_SRC_DIR" ]; then
  mkdir -p "$MU_DEST_DIR"
  for mu_src in "$MU_SRC_DIR"/*.php; do
    [ -f "$mu_src" ] || continue
    mu_dest="$MU_DEST_DIR/$(basename "$mu_src")"
    cmp -s "$mu_src" "$mu_dest" || cp "$mu_src" "$mu_dest"
    # Owned by the host user (the UID www-data was just remapped to) so the
    # copies stay editable and deletable outside the container.
    chown "$HOST_UID:$HOST_GID" "$mu_dest" 2>/dev/null || true
  done

  # Drop copies whose source is gone, so renaming or deleting a sandbox
  # mu-plugin actually takes effect instead of leaving the old one loading
  # forever. Only files we generated are considered — the marker is checked
  # before each removal.
  for mu_old in "$MU_DEST_DIR"/*.php; do
    [ -f "$mu_old" ] || continue
    [ -f "$MU_SRC_DIR/$(basename "$mu_old")" ] && continue
    grep -q '#.local-generated' "$mu_old" 2>/dev/null && rm -f "$mu_old"
  done

  # Earlier versions installed these at the top level. Left in place they would
  # load a second time alongside the local-mu-plugins/ copy, so clear them out —
  # again only if they carry the generated marker, never a file of the project's.
  for mu_legacy in "$MU_ROOT_DIR"/[0-9][0-9]-sandbox-*.php; do
    [ -f "$mu_legacy" ] || continue
    grep -q '#.local-generated' "$mu_legacy" 2>/dev/null && rm -f "$mu_legacy"
  done

  # The stub. "00-" so it sorts ahead of Pantheon's loader.php: the page-cache
  # mu-plugin has to register its filter before Pantheon_Cache is constructed.
  # require, not a closure, so each file runs at global scope exactly as
  # WordPress would have included it.
  cat > "$MU_LOADER" <<'LOADER'
<?php

/**
 * #.local-generated: Automatically generated WordPress must-use plugin.
 * .local manages this file and overwrites it on every container start.
 *
 * Generated by: .local/wp-entrypoint.sh
 *
 * Loads the sandbox mu-plugins that live in local-mu-plugins/. WordPress only
 * loads *.php sitting directly in wp-content/mu-plugins — wp_get_mu_plugins()
 * readdir()s that one directory and does not recurse — so without this stub
 * everything in the subdirectory is invisible to it.
 *
 * The "00-" prefix is load-bearing: mu-plugins load in filename order, and
 * 01-sandbox-page-cache.php must register its filter before Pantheon's
 * loader.php constructs Pantheon_Cache.
 *
 * @package .local
 */

// Sandbox-only, matching the files it loads: a stray copy on a real host does
// nothing at all.
if (getenv('PANTHEON_ENVIRONMENT') !== 'local') {
    return;
}

$local_mu_dir = __DIR__ . '/local-mu-plugins';
if (is_dir($local_mu_dir)) {
    // sort() to make load order match the filename prefixes, the same ordering
    // WordPress applies to the mu-plugins directory itself. glob() is already
    // sorted, but this does not depend on that.
    $local_mu_files = glob($local_mu_dir . '/*.php');
    if ($local_mu_files) {
        sort($local_mu_files);
        foreach ($local_mu_files as $local_mu_file) {
            require_once $local_mu_file;
        }
    }
}

// mu-plugins are included at global scope, so anything left behind becomes a
// global. Clean up after ourselves.
unset($local_mu_dir, $local_mu_files, $local_mu_file);
LOADER
  chown "$HOST_UID:$HOST_GID" "$MU_LOADER" 2>/dev/null || true
  chown "$HOST_UID:$HOST_GID" "$MU_DEST_DIR" 2>/dev/null || true
fi

# Hand off to the stock WordPress entrypoint (which then execs apache2-foreground).
exec docker-entrypoint.sh "$@"
